# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, verbose_name=django.db.models.fields.TextField)),
            ],
            options={
                'db_table': 'group_details',
            },
        ),
        migrations.CreateModel(
            name='UserModelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.GroupModelClass')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
