# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 05:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodelclass',
            name='groups',
            field=models.CharField(default='No Group Selected', max_length=250),
        ),
        migrations.AlterField(
            model_name='usermodelclass',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodelclass',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')]),
        ),
    ]
