# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180604_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelclass',
            name='selectedGroup',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='groupmodelclass',
            name='groups',
            field=models.CharField(max_length=250),
        ),
    ]
