# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180606_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelclass',
            name='selectedGroup',
            field=models.CharField(max_length=50),
        ),
    ]
